/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package optimizationcode;

/**
 *
 * @author lorence
 */
public class MainScreen extends javax.swing.JFrame {

    public static MainScreen sInstance;
    
    public static MainScreen getInstance() {
        if (sInstance == null) {
            sInstance = new MainScreen();
        }
        return sInstance;
    }
    
    public MainScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMain = new javax.swing.JPanel();
        PanelToolBar = new javax.swing.JPanel();
        ToolBar = new javax.swing.JToolBar();
        lbSetting = new javax.swing.JLabel();
        lbButterknife = new javax.swing.JLabel();
        PanelWrapper = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        MenuBar = new javax.swing.JMenuBar();
        ItemMenuFile = new javax.swing.JMenu();
        ItemMenuEdit = new javax.swing.JMenu();
        ItemMenuHelp = new javax.swing.JMenu();
        ItemMenuAbout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(178, 135, 92));
        setMinimumSize(new java.awt.Dimension(1040, 662));
        getContentPane().setLayout(new java.awt.BorderLayout(2, 1));

        PanelMain.setBackground(new java.awt.Color(254, 254, 254));
        PanelMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelMainMouseClicked(evt);
            }
        });
        PanelMain.setLayout(new java.awt.BorderLayout(2, 1));

        PanelToolBar.setLayout(new java.awt.BorderLayout());

        ToolBar.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(179, 179, 179)));
        ToolBar.setRollover(true);

        lbSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_lib.png"))); // NOI18N
        lbSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbSettingMousePressed(evt);
            }
        });
        ToolBar.add(lbSetting);

        lbButterknife.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_lib.png"))); // NOI18N
        lbButterknife.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 10, 0, 0, new java.awt.Color(0, 0, 0)));
        ToolBar.add(lbButterknife);

        PanelToolBar.add(ToolBar, java.awt.BorderLayout.CENTER);

        PanelMain.add(PanelToolBar, java.awt.BorderLayout.NORTH);

        PanelWrapper.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(251, 141, 31));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1039, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
        );

        PanelWrapper.add(jPanel1, java.awt.BorderLayout.CENTER);

        PanelMain.add(PanelWrapper, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelMain, java.awt.BorderLayout.CENTER);

        ItemMenuFile.setText("File");
        MenuBar.add(ItemMenuFile);

        ItemMenuEdit.setText("Edit");
        MenuBar.add(ItemMenuEdit);

        ItemMenuHelp.setText("jMenu3");
        MenuBar.add(ItemMenuHelp);

        ItemMenuAbout.setText("jMenu1");
        MenuBar.add(ItemMenuAbout);

        setJMenuBar(MenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PanelMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMainMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelMainMouseClicked

    private void lbSettingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSettingMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbSettingMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainScreen().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ItemMenuAbout;
    private javax.swing.JMenu ItemMenuEdit;
    private javax.swing.JMenu ItemMenuFile;
    private javax.swing.JMenu ItemMenuHelp;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JPanel PanelMain;
    private javax.swing.JPanel PanelToolBar;
    private javax.swing.JPanel PanelWrapper;
    private javax.swing.JToolBar ToolBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbButterknife;
    private javax.swing.JLabel lbSetting;
    // End of variables declaration//GEN-END:variables
}
