/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.view;

import bean.Coc;
import controller.ControllerCoc;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import utilize.Utils;

/**
 *
 * @author vuongluis
 */
public class FrContent extends javax.swing.JPanel {

    private ControllerCoc controller;

    public FrContent() {
        initComponents();
        controller = new ControllerCoc(tbMain);
        lbImage.setIcon(new ImageIcon(getClass().getResource("/images/imagehere.png")));
        controller.loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLoaiCoc = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        DanhSachCoc = new javax.swing.JPanel();
        labelTenCoc = new javax.swing.JLabel();
        tfTenCoc = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnAdjust = new javax.swing.JButton();
        btnDeleteAll = new javax.swing.JButton();
        btnDeleteAll1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMain = new javax.swing.JTable();
        DacTrungHinhHoc = new javax.swing.JPanel();
        pnDacTrungHinhHoc = new javax.swing.JPanel();
        lbLoaiCoc = new javax.swing.JLabel();
        rdCocEp = new javax.swing.JRadioButton();
        rdCocKhoanNhoi = new javax.swing.JRadioButton();
        lbImage = new javax.swing.JLabel();
        lbLoaiTietDien = new javax.swing.JLabel();
        cbLoaiTietDien = new javax.swing.JComboBox<>();
        lbLoaiTietDien1 = new javax.swing.JLabel();
        lbA1 = new javax.swing.JLabel();
        tfA1 = new javax.swing.JTextField();
        lbDoSauDauCoc = new javax.swing.JLabel();
        lbDoSauMuiCoc = new javax.swing.JLabel();
        tfDoSauDauCoc = new javax.swing.JTextField();
        tfDoSauMuiCoc = new javax.swing.JTextField();
        pnSucChieuTai = new javax.swing.JPanel();
        pnCommon = new javax.swing.JPanel();
        pnVatLieu = new javax.swing.JPanel();
        lbCapBeTong = new javax.swing.JLabel();
        cbCapBeTong = new javax.swing.JComboBox<>();
        lbCapBeTong1 = new javax.swing.JLabel();
        cbMacThep = new javax.swing.JComboBox<>();
        pnThepChinh = new javax.swing.JPanel();
        lbCapBeTong2 = new javax.swing.JLabel();
        lbCapBeTong3 = new javax.swing.JLabel();
        cbDuongKinhThep = new javax.swing.JComboBox<>();
        tfSoThanhThep = new javax.swing.JTextField();
        pnThepChinh1 = new javax.swing.JPanel();
        tfSucChieTaiVatLieu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSucChieuTaiVatLieu = new javax.swing.JButton();

        setBackground(new java.awt.Color(242, 242, 242));
        setMaximumSize(new java.awt.Dimension(846, 498));
        setMinimumSize(new java.awt.Dimension(846, 498));
        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSplitPane1.setOneTouchExpandable(true);

        DanhSachCoc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách Cọc", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        DanhSachCoc.setMaximumSize(new java.awt.Dimension(301, 496));
        DanhSachCoc.setMinimumSize(new java.awt.Dimension(301, 496));

        labelTenCoc.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelTenCoc.setText("Tên cọc ......");

        tfTenCoc.setText("C1");
        tfTenCoc.setMinimumSize(new java.awt.Dimension(6, 24));
        tfTenCoc.setPreferredSize(new java.awt.Dimension(6, 24));

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btnAdjust.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAdjust.setText("Hiệu chỉnh");

        btnDeleteAll.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDeleteAll.setText("Xóa hết");

        btnDeleteAll1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDeleteAll1.setText("Xóa");

        tbMain.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tbMain.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Tên Cọc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbMain);

        javax.swing.GroupLayout DanhSachCocLayout = new javax.swing.GroupLayout(DanhSachCoc);
        DanhSachCoc.setLayout(DanhSachCocLayout);
        DanhSachCocLayout.setHorizontalGroup(
            DanhSachCocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DanhSachCocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DanhSachCocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DanhSachCocLayout.createSequentialGroup()
                        .addComponent(labelTenCoc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfTenCoc, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DanhSachCocLayout.createSequentialGroup()
                        .addGroup(DanhSachCocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DanhSachCocLayout.createSequentialGroup()
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(btnAdjust, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DanhSachCocLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnDeleteAll1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDeleteAll)))
                        .addContainerGap())))
        );
        DanhSachCocLayout.setVerticalGroup(
            DanhSachCocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DanhSachCocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DanhSachCocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTenCoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTenCoc))
                .addGap(18, 18, 18)
                .addGroup(DanhSachCocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdjust, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DanhSachCocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteAll1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteAll, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jSplitPane1.setLeftComponent(DanhSachCoc);

        DacTrungHinhHoc.setBackground(new java.awt.Color(242, 242, 242));
        DacTrungHinhHoc.setMaximumSize(new java.awt.Dimension(2147483647, 496));
        DacTrungHinhHoc.setMinimumSize(new java.awt.Dimension(12, 496));
        DacTrungHinhHoc.setPreferredSize(new java.awt.Dimension(537, 496));
        DacTrungHinhHoc.setLayout(new java.awt.BorderLayout());

        pnDacTrungHinhHoc.setBackground(new java.awt.Color(242, 242, 242));
        pnDacTrungHinhHoc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Đặc trưng hình học", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lbLoaiCoc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbLoaiCoc.setText("Loại cọc");

        btnLoaiCoc.add(rdCocEp);
        rdCocEp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdCocEp.setSelected(true);
        rdCocEp.setText("Cọc ép");

        btnLoaiCoc.add(rdCocKhoanNhoi);
        rdCocKhoanNhoi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdCocKhoanNhoi.setText("Cọc khoan nhồi");

        lbImage.setBackground(new java.awt.Color(255, 0, 204));

        lbLoaiTietDien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbLoaiTietDien.setText("Loại tiết diện");

        cbLoaiTietDien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hình vuông", "Hình tròn", " " }));
        cbLoaiTietDien.setMinimumSize(new java.awt.Dimension(56, 24));
        cbLoaiTietDien.setPreferredSize(new java.awt.Dimension(56, 24));

        lbLoaiTietDien1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbLoaiTietDien1.setText("Kích thước tiết diện");

        lbA1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbA1.setText("A1 (mm)");

        tfA1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfA1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfA1.setText("300");
        tfA1.setMinimumSize(new java.awt.Dimension(6, 24));
        tfA1.setPreferredSize(new java.awt.Dimension(27, 24));

        lbDoSauDauCoc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDoSauDauCoc.setText("Độ sâu đầu cọc. (m)");

        lbDoSauMuiCoc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDoSauMuiCoc.setText("Độ sâu mũi cọc. (m)");

        tfDoSauDauCoc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfDoSauDauCoc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfDoSauDauCoc.setText("0");
        tfDoSauDauCoc.setMinimumSize(new java.awt.Dimension(6, 24));
        tfDoSauDauCoc.setPreferredSize(new java.awt.Dimension(27, 24));

        tfDoSauMuiCoc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfDoSauMuiCoc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfDoSauMuiCoc.setText("50");
        tfDoSauMuiCoc.setMinimumSize(new java.awt.Dimension(6, 24));
        tfDoSauMuiCoc.setPreferredSize(new java.awt.Dimension(27, 24));

        javax.swing.GroupLayout pnDacTrungHinhHocLayout = new javax.swing.GroupLayout(pnDacTrungHinhHoc);
        pnDacTrungHinhHoc.setLayout(pnDacTrungHinhHocLayout);
        pnDacTrungHinhHocLayout.setHorizontalGroup(
            pnDacTrungHinhHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDacTrungHinhHocLayout.createSequentialGroup()
                .addGroup(pnDacTrungHinhHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDacTrungHinhHocLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnDacTrungHinhHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbLoaiCoc)
                            .addComponent(lbLoaiTietDien)
                            .addComponent(lbLoaiTietDien1)))
                    .addGroup(pnDacTrungHinhHocLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(lbA1))
                    .addGroup(pnDacTrungHinhHocLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbDoSauDauCoc))
                    .addGroup(pnDacTrungHinhHocLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbDoSauMuiCoc)))
                .addGroup(pnDacTrungHinhHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDacTrungHinhHocLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(rdCocEp))
                    .addGroup(pnDacTrungHinhHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnDacTrungHinhHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rdCocKhoanNhoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDacTrungHinhHocLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(tfA1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(cbLoaiTietDien, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfDoSauDauCoc, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfDoSauMuiCoc, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62)
                .addComponent(lbImage, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        pnDacTrungHinhHocLayout.setVerticalGroup(
            pnDacTrungHinhHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDacTrungHinhHocLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnDacTrungHinhHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnDacTrungHinhHocLayout.createSequentialGroup()
                        .addGroup(pnDacTrungHinhHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbLoaiCoc)
                            .addComponent(rdCocEp))
                        .addGap(2, 2, 2)
                        .addComponent(rdCocKhoanNhoi)
                        .addGap(35, 35, 35)
                        .addGroup(pnDacTrungHinhHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbLoaiTietDien)
                            .addComponent(cbLoaiTietDien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbLoaiTietDien1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnDacTrungHinhHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbA1)
                            .addComponent(tfA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(pnDacTrungHinhHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDoSauDauCoc)
                            .addComponent(tfDoSauDauCoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(pnDacTrungHinhHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDoSauMuiCoc)
                            .addComponent(tfDoSauMuiCoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 42, Short.MAX_VALUE)))
                .addContainerGap())
        );

        DacTrungHinhHoc.add(pnDacTrungHinhHoc, java.awt.BorderLayout.PAGE_START);

        pnSucChieuTai.setBackground(new java.awt.Color(242, 242, 242));
        pnSucChieuTai.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sức chịu tải theo vật liệu", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        pnSucChieuTai.setPreferredSize(new java.awt.Dimension(200, 402));
        pnSucChieuTai.setLayout(new java.awt.BorderLayout());

        pnVatLieu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vật liệu", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        lbCapBeTong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCapBeTong.setText("Cấp bê tông");

        cbCapBeTong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbCapBeTong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B15", "B20", "B22.5", "B25", "B30", "B35", "B40", "B45", "B50" }));
        cbCapBeTong.setMinimumSize(new java.awt.Dimension(63, 24));
        cbCapBeTong.setPreferredSize(new java.awt.Dimension(63, 24));

        lbCapBeTong1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCapBeTong1.setText("Mác thép");

        cbMacThep.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbMacThep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A-II", "A-III" }));
        cbMacThep.setMinimumSize(new java.awt.Dimension(63, 24));
        cbMacThep.setPreferredSize(new java.awt.Dimension(63, 24));

        javax.swing.GroupLayout pnVatLieuLayout = new javax.swing.GroupLayout(pnVatLieu);
        pnVatLieu.setLayout(pnVatLieuLayout);
        pnVatLieuLayout.setHorizontalGroup(
            pnVatLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnVatLieuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnVatLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnVatLieuLayout.createSequentialGroup()
                        .addGroup(pnVatLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCapBeTong)
                            .addComponent(lbCapBeTong1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnVatLieuLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(pnVatLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbCapBeTong, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbMacThep, javax.swing.GroupLayout.Alignment.TRAILING, 0, 108, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnVatLieuLayout.setVerticalGroup(
            pnVatLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnVatLieuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbCapBeTong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCapBeTong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbCapBeTong1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbMacThep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnThepChinh.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thép chính", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        lbCapBeTong2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCapBeTong2.setText("Số thanh thép");

        lbCapBeTong3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCapBeTong3.setText("Đường kính thép");

        cbDuongKinhThep.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbDuongKinhThep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "14", "16", "18", "20", "22", "25", "28", "30", "32", " ", " " }));
        cbDuongKinhThep.setMinimumSize(new java.awt.Dimension(63, 24));
        cbDuongKinhThep.setPreferredSize(new java.awt.Dimension(63, 24));

        tfSoThanhThep.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfSoThanhThep.setMinimumSize(new java.awt.Dimension(6, 24));
        tfSoThanhThep.setPreferredSize(new java.awt.Dimension(59, 24));

        javax.swing.GroupLayout pnThepChinhLayout = new javax.swing.GroupLayout(pnThepChinh);
        pnThepChinh.setLayout(pnThepChinhLayout);
        pnThepChinhLayout.setHorizontalGroup(
            pnThepChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThepChinhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThepChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThepChinhLayout.createSequentialGroup()
                        .addGroup(pnThepChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCapBeTong2)
                            .addComponent(lbCapBeTong3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThepChinhLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(pnThepChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbDuongKinhThep, javax.swing.GroupLayout.Alignment.TRAILING, 0, 108, Short.MAX_VALUE)
                            .addComponent(tfSoThanhThep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnThepChinhLayout.setVerticalGroup(
            pnThepChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThepChinhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbCapBeTong2)
                .addGap(10, 10, 10)
                .addComponent(tfSoThanhThep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbCapBeTong3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDuongKinhThep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnThepChinh1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SCT theo VL", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        tfSucChieTaiVatLieu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfSucChieTaiVatLieu.setMinimumSize(new java.awt.Dimension(6, 24));
        tfSucChieTaiVatLieu.setPreferredSize(new java.awt.Dimension(6, 24));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("(kN)");

        javax.swing.GroupLayout pnThepChinh1Layout = new javax.swing.GroupLayout(pnThepChinh1);
        pnThepChinh1.setLayout(pnThepChinh1Layout);
        pnThepChinh1Layout.setHorizontalGroup(
            pnThepChinh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThepChinh1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfSucChieTaiVatLieu, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1))
        );
        pnThepChinh1Layout.setVerticalGroup(
            pnThepChinh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThepChinh1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnThepChinh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSucChieTaiVatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSucChieuTaiVatLieu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSucChieuTaiVatLieu.setText("Tính SCT Vật Liệu");
        btnSucChieuTaiVatLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performChieuTaiVL(evt);
            }
        });

        javax.swing.GroupLayout pnCommonLayout = new javax.swing.GroupLayout(pnCommon);
        pnCommon.setLayout(pnCommonLayout);
        pnCommonLayout.setHorizontalGroup(
            pnCommonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCommonLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(pnCommonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSucChieuTaiVatLieu)
                    .addGroup(pnCommonLayout.createSequentialGroup()
                        .addComponent(pnVatLieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnThepChinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnThepChinh1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(5, 5, 5))
        );
        pnCommonLayout.setVerticalGroup(
            pnCommonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCommonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCommonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnVatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnCommonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pnThepChinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnThepChinh1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(btnSucChieuTaiVatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnSucChieuTai.add(pnCommon, java.awt.BorderLayout.CENTER);

        DacTrungHinhHoc.add(pnSucChieuTai, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(DacTrungHinhHoc);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed

        String tenCoc = tfTenCoc.getText();
        String loaiCoc = rdCocEp.isSelected() ? "Cọc ép" : "Cọc khoan nhồi";
        String loaiTietDien = cbLoaiTietDien.getSelectedItem().toString();
        Double a1 = Double.parseDouble(tfA1.getText());
        Double doSauDauCoc = Double.parseDouble(tfDoSauDauCoc.getText());
        Double doSauMuiCoc = Double.parseDouble(tfDoSauMuiCoc.getText());
        String capBeTong = cbCapBeTong.getSelectedItem().toString();
        String macThep = cbMacThep.getSelectedItem().toString();
        Double soThanhThep = Double.parseDouble(tfSoThanhThep.getText());
        Double duongKinhThep = Double.parseDouble(cbDuongKinhThep.getSelectedItem().toString());
        Coc obj = new Coc(tenCoc, loaiCoc, loaiTietDien, a1, doSauDauCoc, doSauMuiCoc, capBeTong, macThep, soThanhThep, duongKinhThep);
    }//GEN-LAST:event_btThemActionPerformed

    private void performChieuTaiVL(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performChieuTaiVL

        Double phi = 1.0;
        Double m1 = 0.85, m2 = 0.7;
        Double Ra = getMacThep(cbMacThep.getSelectedItem().toString()) * 1000.0;
        Double Rb = getCapDoBeTong(cbCapBeTong.getSelectedItem().toString()) * 1000.0;
        // Coc Ep
        Double Fa = Double.parseDouble(tfSoThanhThep.getText())*Math.PI*Double.parseDouble(cbDuongKinhThep.getSelectedItem().toString())*Double.parseDouble(cbDuongKinhThep.getSelectedItem().toString())/(4.0*1000000.0);
        
        Double Fb = 0.0;
        if (rdCocEp.isSelected()) {
            Fb = Double.parseDouble(tfA1.getText())*Double.parseDouble(tfA1.getText())/(1000000.0) - Fa;
        } else {
            Fb = Math.PI*Double.parseDouble(cbDuongKinhThep.getSelectedItem().toString())*Double.parseDouble(cbDuongKinhThep.getSelectedItem().toString())/(4.0*1000000.0) - Fa;
        }   
        Double result = phi*(m1*m2*Rb*Fb + Ra*Fa);
        tfSucChieTaiVatLieu.setText(String.format("%.2f", result));
    }//GEN-LAST:event_performChieuTaiVL

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DacTrungHinhHoc;
    private javax.swing.JPanel DanhSachCoc;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdjust;
    private javax.swing.JButton btnDeleteAll;
    private javax.swing.JButton btnDeleteAll1;
    private javax.swing.ButtonGroup btnLoaiCoc;
    private javax.swing.JButton btnSucChieuTaiVatLieu;
    private javax.swing.JComboBox<String> cbCapBeTong;
    private javax.swing.JComboBox<String> cbDuongKinhThep;
    private javax.swing.JComboBox<String> cbLoaiTietDien;
    private javax.swing.JComboBox<String> cbMacThep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel labelTenCoc;
    private javax.swing.JLabel lbA1;
    private javax.swing.JLabel lbCapBeTong;
    private javax.swing.JLabel lbCapBeTong1;
    private javax.swing.JLabel lbCapBeTong2;
    private javax.swing.JLabel lbCapBeTong3;
    private javax.swing.JLabel lbDoSauDauCoc;
    private javax.swing.JLabel lbDoSauMuiCoc;
    private javax.swing.JLabel lbImage;
    private javax.swing.JLabel lbLoaiCoc;
    private javax.swing.JLabel lbLoaiTietDien;
    private javax.swing.JLabel lbLoaiTietDien1;
    private javax.swing.JPanel pnCommon;
    private javax.swing.JPanel pnDacTrungHinhHoc;
    private javax.swing.JPanel pnSucChieuTai;
    private javax.swing.JPanel pnThepChinh;
    private javax.swing.JPanel pnThepChinh1;
    private javax.swing.JPanel pnVatLieu;
    private javax.swing.JRadioButton rdCocEp;
    private javax.swing.JRadioButton rdCocKhoanNhoi;
    private javax.swing.JTable tbMain;
    private javax.swing.JTextField tfA1;
    private javax.swing.JTextField tfDoSauDauCoc;
    private javax.swing.JTextField tfDoSauMuiCoc;
    private javax.swing.JTextField tfSoThanhThep;
    private javax.swing.JTextField tfSucChieTaiVatLieu;
    private javax.swing.JTextField tfTenCoc;
    // End of variables declaration//GEN-END:variables

    private Double getCapDoBeTong(String capDoBeTong) {
        switch (capDoBeTong) {
            case "B15":
                return 8.5;
            case "B20":
                return 11.5;
            case "B25":
                return 14.5;
            case "B30":
                return 17.0;
            case "B35":
                return 19.5;
            case "B40":
                return 22.0;
            case "B45":
                return 25.0;
        }
        return 0.0;
    }
    
    private Double getMacThep(String macThep) {
        switch (macThep) {
            case "AII":
                return 280.0;
            case "AIII":
                return 365.0;
        }
        return 0.0;
    }
}
